### PR TITLE
Restored Functionality for Modern Flickr

### PR DESCRIPTION
**Pull request by mariten**
## Summary

Hi @aemkei I fixed this bookmarklet to work with Flickr again, can you look it over?

I have tested it in the newest versions of Firefox, Chrome, Safari, and IE and it works on all.

You can test it here

```
javascript:%20(function(){if(window.geocoding_bookmarklet){geocoding_bookmarklet.reload();return;}%20var%20script=document.createElement("script");script.src="https://rawgit.com/mariten/flickr_geocoding_bookmarklet/fix-for-new-flickr/main.js?"%20+%20Math.random();document.body.appendChild(script);})();
```

Thanks! :beers: 
## Introduction

I am a long-time user of this bookmarklet and have geotagged maybe close to 1000 pictures with it - thanks for making it!  I use Flickr a lot, and most of my pictures are taken in Japan because I live there.  Though Google and Yahoo Japan have very details maps of Japan, Flickr uses Yahoo's US map for Japan which has very poor details, and makes geotagging a pain.  Being able to place the marker using Google Maps makes my life much easier, and so I am a big fan of this script.
## Problems

However, the bookmarklet hasn't been working recently.  Looking at the chat on Flickr, it hasn't worked for about a year.  I'm a web developer so I looked into it and the main problems were
1. Flickr now uses HTTPS across the board, but this script includes other scripts and files from HTTP sources leading to security warnings/rejections by most modern browsers.
2. The Flickr API login mechanism has changed, and so the parameters to pass to API calls (and where to find them on the source page) have also changed.

This pull request fixes these issues.
#### Fix HTTPS Issues
- All scripts, images, and API calls are now done via HTTPS
- Some browsers will not allow a script from GitHub to be directly included/executed for security reasons because GitHub returns a MIME type of "text/plain" no matter what the file extension is.  There is a service called "Raw GitHub" that acts like a CDN and returns JS files stored on GitHub with the correct MIME type of "application/javascript", so I've changed the bookmarklet's text to make use of that service.  For more information see http://stackoverflow.com/questions/14033281/including-javascript-files-from-github-into-html-pages
#### Updated Parameters Passed to API
- `magic_cookie`, `api_secret`, `auth_token`, `auth_hash`, and `clientType` are no longer necesssary.
- Instead, `csrf` must be read from the page's internal DOM and passed to the Ajax calls to the API.  This `csrf`, along with api_key`, are the only two credentials necessary.
- The `get_secrets()` method cannot read all the data out of a JSON from the last `<script>` tag, it must pull this information (including `OWNER_NSID` and `USER_NSID`) from other sources now such as HTML tags or global JS variables.
- The template `www.flickr.com/flickrmap_locationconfirm_fragment.gne` is no longer usable, so I removed the location confirmation check.  The bookmarklet works fine without it.
#### Fixed Initial Position Fetch
- URL parameter names have changed (for example, `clat` changed to `fLat`)
- Fixed `getQueryVariable` to work if a variable is the first variable in the query string (not after a `&` char)
#### Fixed some Design Issues with the New Flickr
- Had to change the height of the main panel
- "Maximize" overflows the screen now, so removed the option.
#### Misceallenous
- Fixed a few other small things.

Thanks!

### CODE REVIEW

**Comment by aemkei** [comment]
Whooaa! This is super awesome! Thanks so much for fixing that issue. 

Sorry: I moved from Flickr to G+ some time ago so I was not involved anymore.

**Comment by mariten** [comment]
Thanks!
I still use Flickr as my primary service for uploading nicer or more photographic pictures (as opposed to pictures of friends and whatnot for which I usually use FB).  So, as a user of this bookmarklet, I will keep an eye on it from time to time.

**Comment by mariten** [comment]
@aemkei Would you mind updating the bookmarklet link on the sumaato page?
http://labs.sumaato.net/tools/flickr_geocode_bookmarklet/
Since the top message in the Flickr forum about the bookmarklet still links to that page, most people are probably still grabbing it from there.

It needs to be set to the new link I added to the README:

```
javascript:%20(function(){if(window.geocoding_bookmarklet){geocoding_bookmarklet.reload();return;}%20var%20script=document.createElement("script");script.src="https://cdn.rawgit.com/ubilabs/flickr_geocoding_bookmarklet/master/main.js?"%20+%20Math.random();document.body.appendChild(script);})();
```

**Comment by aemkei** [comment]
Sorry, I had to find the right person to update the old server.

It is done now: http://labs.sumaato.net/tools/flickr_geocode_bookmarklet/

Thanks again for the great effort!

**Comment by mariten** [comment]
:+1:

**Pull request merged**
